spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/ras"
    username: "ras-user"
    password: "ras-pass"

hmpps:
  auth:
    url: http://localhost:9090/auth
  sqs:
    provider: localstack
    queues:
      prisonerlistener:
        queueName: "prisonerlistener-${random.uuid}"
        dlqName: "prisonerlistener-dlq-${random.uuid}"
        subscribeTopicId: hmppsdomaintopic
        subscribeFilter: "{\"eventType\":[\"prison-offender-events.prisoner.booking.moved\"]}"
        dlqMaxReceiveCount: 3
        visibilityTimeout: 120
    topics:
      hmppsdomaintopic:
        arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}

prison:
  api:
    url: http://localhost:8332

document:
  management:
    api:
      url: http://localhost:8442

adjustments:
  api:
    url: http://localhost:8552

ingress:
  url: localhost:8080